# -*- coding: utf-8 -*-
"""AI 기초.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aFvHYZwlvCevZ-psBGt07OoAHg98fat1
"""

from google.colab import drive #구글 드라이브 연동

drive.mount("/content/gdrive")

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers.legacy import Adam
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dropout, MaxPooling2D, Flatten, Dense
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

!gdown https://drive.google.com/uc?id=1AbdgJGssMVtp8qokqyR8thfl1Ko-yC26

path = '/content/서울시 자치구 목적별 CCTV 설치 수량_221231기준.csv'

cctv = pd.read_csv(path, encoding = 'cp949')
cctv.head()

cctv.head(10)

cctv.info()

cctv.isna()

cctv.isna().sum()

import matplotlib as mpl
import matplotlib.pyplot as plt

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

plt.rc('font', family='NanumBarunGothic')

plt.figure(figsize=(12,4))
plt.title('각 자치구별 cctv 개수', fontsize=16)
plt.plot(cctv['구분'],cctv['총계'])
plt.show()

plt.figure(figsize=(12,4))
plt.title('각 자치구별 쓰레기무단투기용 cctv개수', fontsize=16)
plt.plot(cctv['구분'],cctv['쓰레기\n무단투기'],color='green')
plt.show()

plt.figure(figsize=(12,4))
plt.title('각 자치구별 쓰레기무단투기용 cctv개수', fontsize=16)
plt.boxplot([cctv['총계'], cctv['쓰레기\n무단투기']])
plt.show()

